steps:
  # Install VS Code Extension Manager (vsce >= v2.26.1 needed) and dependencies
  - script: |
      cd $(Build.SourcesDirectory)
      npm install -g @vscode/vsce
      npm install
    displayName: 'Install vsce and dependencies'

  # Publish
  - task: AzureCLI@2
    displayName: 'Publish using managed identity'
    inputs:
      azureSubscription: Publishing Extensions
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        cd $(Build.SourcesDirectory)
        npm run build
        vsce publish --azure-credential
